language: cpp

env:
  global:
    - MAKEFLAGS="-j 2"

addons:
  homebrew:
    packages:
      - ghostscript
      - md5sha1sum

matrix:
  include:
    - os: osx
      osx_image: xcode11.3
      before_install: ./travis-ci/osx/before_install.sh
      before_script: ./travis-ci/osx/before_script.sh
      script: ./travis-ci/osx/script.sh
      after_failure: ./travis-ci/osx/after_failure.sh
    - os: linux
      dist: trusty
      services: docker
      env:
        - MIKTEX_LINUX_DIST=ubuntu
        - MIKTEX_LINUX_DIST_VERSION=18.04
        - MIKTEX_LINUX_DIST_CODE_NAME=bionic
      script: ./travis-ci/docker/script.sh
      after_failure: ./travis-ci/docker/after_failure.sh

notifications:
  email: false
